### ISSUE TITLE
17 errors

### ISSUE THREAD

**Issue by Theo-denBlanken** [LeonBoussen/ontwerp#1]
bij validatie

**Comment by LeonBoussen** [comment]
de errors zijn opgelost.

**Comment by Theo-denBlanken** [comment]
Als ik jouw online link http://30542.hosts1.ma-cloud.nl/F1M1Ontwerp/ontwerp/materiaal-oefening-menu/index.html valideer zie nog steeds die fouten!!!


Met vriendelijke groeten,

--

[ma-logo]
Theo den Blanken

[Theo]<http://blanken5.home.xs4all.nl/>
docent
Mediadeveloper
Mediacollege Amsterdam
[Twitter]<https://twitter.com/theodenblanken/> [WordPress] <http://bla.hosts.ma-cloud.nl/>


Van: Leon <notifications@github.com>
Datum: maandag, 18 januari 2021 om 14:33
Aan: LeonBoussen/ontwerp <ontwerp@noreply.github.com>
CC: Theo den Blanken <T.denBlanken@ma-web.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [LeonBoussen/ontwerp] 17 errors (#1)

Closed #1<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLeonBoussen%2Fontwerp%2Fissues%2F1&data=04%7C01%7Ct.denblanken%40ma-web.nl%7C528a58120b724f9e675a08d8bbb5a4ac%7C8e600f9230df4667b7c03f2595f3f12b%7C0%7C0%7C637465736118849022%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pIEborCw8vOrlMdvpeYViTgn%2BJbwOozDwqJ1%2FT3Plig%3D&reserved=0>.
